$font = Iosevka Nerd Font
$goldAccent = rgb(249, 226, 175)
$darkBlack = rgb(30, 30, 46)
$textWhite = rgb(205, 214, 244)

general {
    hide_cursor = true
    ignore_empty_input = true
}

background {
    monitor =
    path = /home/aradhy/Pictures/Wallpapers/sports.png
    blur_passes = 2
    color = rgb(0D1017)
}

label {
    monitor =
    text = cmd[update:30000] echo "<b>$(date +"%H:%M")</b>"
    color = $goldAccent
    font_size = 90
    font_family = $font
    position = 0, 120
    halign = center
    valign = center
}

label {
    monitor = 
    text = cmd[update:43200000] echo "$(date +"%A, %d %B")"
    color = $textWhite
    font_size = 20
    font_family = $font
    position = 0, 30
    halign = center
    valign = center
}
input-field {
    monitor =
    size = 275, 50
    outline_thickness = 2
    dots_size = 0.2
    dots_spacing = 0.2
    dots_center = true
    outer_color = $goldAccent
    inner_color = $darkBlack
    font_color = $textWhite
    fade_on_empty = false
    placeholder_text = <i>Enter Password...</i>
    hide_input = false
    fail_color = rgb(243, 139, 168)
    fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
    capslock_color = rgb(166, 227, 161)
    position = 0, -50
    halign = center
    valign = center
}
